export { default as About } from './about/about'
export { default as Contact } from './contact/contact'
export { default as Footer } from './footer/footer'
export { default as Header } from './header/header'
export { default as Newsletter } from './newsletter/newsletter'
export { default as References } from './references/references'
export { default as Services } from './services/services'
export { default as Stats } from './stats/stats'
